[program:perfume-lab-pos-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/perfume-lab-pos/backend-laravel/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/perfume-lab-pos/backend-laravel/storage/logs/queue-worker.log
stopwaitsecs=3600
