server {
    listen 80;
    server_name api.perfumelabpos.com;

    root /var/www/perfume-lab-pos/backend-laravel/public;
    index index.php index.html;

    charset utf-8;

    access_log /var/log/nginx/perfume-lab-pos.access.log;
    error_log /var/log/nginx/perfume-lab-pos.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
